workspace(name = "example")

http_archive(
    name = "io_grpc_grpc_java",
    strip_prefix = "grpc-java-1.17.1",
    urls = ["https://github.com/grpc/grpc-java/archive/v1.17.1.zip"],
)

load("@io_grpc_grpc_java//:repositories.bzl", "grpc_java_repositories")

grpc_java_repositories()

maven_jar(
    name = "io_grpc_grpc_java_api_checker",
    artifact = "io.grpc:grpc-java-api-checker:1.1.0",
    sha1 = "d0c4b2979fbd7127d0c3e587f9076ead9457d344",
)
